/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class headsets_epoc_EpocConnector */

#ifndef _Included_headsets_epoc_EpocConnector
#define _Included_headsets_epoc_EpocConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     headsets_epoc_EpocConnector
 * Method:    helloTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_headsets_epoc_EpocConnector_helloTest
  (JNIEnv *, jobject);

/*
 * Class:     headsets_epoc_EpocConnector
 * Method:    readData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_headsets_epoc_EpocConnector_readData
  (JNIEnv *, jobject);

/*
 * Class:     headsets_epoc_EpocConnector
 * Method:    connectHeadsets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_headsets_epoc_EpocConnector_connectHeadsets
  (JNIEnv *, jobject);

/*
 * Class:     headsets_epoc_EpocConnector
 * Method:    disconnectHeadsets
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_headsets_epoc_EpocConnector_disconnectHeadsets
  (JNIEnv *, jobject);

/*
 * Class:     headsets_epoc_EpocConnector
 * Method:    readQuality
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_headsets_epoc_EpocConnector_readQuality
  (JNIEnv *, jobject);

/*
 * Class:     headsets_epoc_EpocConnector
 * Method:    readBattery
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_headsets_epoc_EpocConnector_readBattery
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
